import ConfigureComponent from "@/components/configuration/ConfigureComponent";
import Navbar from "@/components/Navbar";
import SideBar from "@/components/SideBar";
import { isUnAuthRoute } from "@/config/routesConfig";
import ReduxProvider from "@/redux/ReduxProvider";
import "./globals.css";

export const metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className="bg-white">
          <ConfigureComponent>{children}</ConfigureComponent>
        </body>
      </html>
    </ReduxProvider>
  );
}
